"""
Django settings for corporate_portal project.

Generated by 'django-admin startproject' using Django 4.0.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'your-secret-key'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'portal',  # Add your app here
    'axes',    # Proteção de Força Bruta
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',  # Middleware para barrar acessos após falhas
]

ROOT_URLCONF = 'corporate_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'corporate_portal.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configurações de Cibersegurança (django-axes e Sessões)
# ----------------------------------------------------
# 1. Proteção contra Força Bruta (django-axes)
AXES_FAILURE_LIMIT = 5  # Bloqueia após 5 tentativas erradas
AXES_COOLOFF_TIME = 1   # Tempo de bloqueio de 1 hora
AXES_LOCKOUT_PARAMETERS = ["ip_address", "username"]  # Bloqueia apenas aquele usuário naquele computador (para que um não trave o outro)
AXES_LOCKOUT_CALLABLE = "portal.security.custom_lockout_view"  # Tela customizada de bloqueio e JSON

# 2. Segurança de Sessões (Timeout Automático)
SESSION_COOKIE_AGE = 1800  # Tempo inativo expira a sessão em 30 minutos (em segundos)
SESSION_SAVE_EVERY_REQUEST = True  # Renova os 30 min cada vez que ele clica no site
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Se fechar o navegador, desloga na hora

# 3. Escudos de Navegador (Security Headers)
# Diz para o navegador que este site contém informações confidenciais
SECURE_BROWSER_XSS_FILTER = True  # Ativa o filtro anti-Cross Site Scripting (XSS) nativo do navegador
SECURE_CONTENT_TYPE_NOSNIFF = True  # Impede ataques que se disfarçam de imagens para rodar vírus
X_FRAME_OPTIONS = 'DENY'  # Impede "Clickjacking" (outros sites não podem clonar o portal)

# Quando o site for pro ar e tiver HTTPS (Certificado SSL), essas configurações devem ser ativadas
# SECURE_SSL_REDIRECT = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# Backends de Autenticação
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',  # O segurança do Axes analisa o login primeiro
    'django.contrib.auth.backends.ModelBackend',
]