# Generated by Django 6.0.3 on 2026-04-03 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_perfilusuario_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='data_criacao',
        ),
        migrations.CreateModel(
            name='RegistroHumor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nivel', models.IntegerField(choices=[(1, 'Péssimo'), (2, 'Ruim'), (3, 'Neutro'), (4, 'Bom'), (5, 'Excelente')])),
                ('anotacao', models.TextField(blank=True, null=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_humor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Humor',
                'verbose_name_plural': 'Registros de Humor',
                'ordering': ['-data'],
                'unique_together': {('user', 'data')},
            },
        ),
    ]
